sudo: false
language: ruby

branches:
  only:
    - master

script:
  - echo 'Build!'

deploy:
  provider: pages
  local_dir: pages
  target_branch: gh-pages-test
  skip_cleanup: true
  project_name: "Let's see what it does"
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
