sudo: false
language: ruby

branches:
  only:
    - master

before_install:
  - set -x -e

script:
  - echo 'Build!'

deploy:
  provider: pages
  local_dir: pages
  target_branch: gh-pages-test
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
